### ISSUE TITLE
[BUG] Nginx v1.8 compile errors

### ISSUE THREAD

**Issue by soakes** [samizdatco/nginx-http-auth-digest#29]
Hi guys,

I am trying to compile this module using a Debian 8 (Jessie) machine, however it keeps erroring.  I have tried looking over the code but it doesn't make too much sence to be due to I know very little C.

My question is... Has anyone managed to get this working using Nginx v1.8?

I highly suspect the issue is to do with the version differeces in the http_basic_auth module and not the OS version which makes this incompatible in some way. 

It would be great to see this module working with later/latest versions of Nginx.

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
        -o objs/addon/nginx-http-auth-digest/ngx_http_auth_digest_module.o \
        ../nginx-http-auth-digest/ngx_http_auth_digest_module.c
../nginx-http-auth-digest/ngx_http_auth_digest_module.c: In function ‘ngx_http_auth_digest_decode_auth’:
../nginx-http-auth-digest/ngx_http_auth_digest_module.c:297:26: error: variable ‘p’ set but not used [-Werror=unused-but-set-variable]
   u_char *start, *last, *p;
                          ^
cc1: all warnings being treated as errors
objs/Makefile:1431: recipe for target 'objs/addon/nginx-http-auth-digest/ngx_http_auth_digest_module.o' failed
make[3]: *** [objs/addon/nginx-http-auth-digest/ngx_http_auth_digest_module.o] Error 1
make[3]: Leaving directory '/usr/src/nginx-1.8.0'
Makefile:8: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Leaving directory '/usr/src/nginx-1.8.0'
dh_auto_build: make -j1 returned exit code 2
debian/rules:19: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/usr/src/nginx-1.8.0'
debian/rules:11: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

Kind Regards,

Simon

**Comment by putnamhill** [comment]
I had a similar problem (maybe the same). After getting it to compile with with nginx 1.4 and 1.7, the login credentials were always rejected.

I've compiled https://github.com/atomx/nginx-http-auth-digest with nginx 1.9.6 on and it works fine.

**Comment by soakes** [comment]
Thank you very much for the alternative module link, will give it a whirl shortly.

**Comment by ErikDubbelboer** [comment]
As you can see the last commit on this repository was almost 4 years ago. It's not being maintained anymore.

https://github.com/atomx/nginx-http-auth-digest is currently the most up-to-date version with all bugfixes and since we use this for our company we plan to keep it up to date.

**Comment by soakes** [comment]
Hi @ErikDubbelboer,

Sorry, I only just noticed your message, its been a busy week.

I must admit that I did not notice that the last commit on this repo was so old.   I originally found the module though nginx's home page directly and cloned the repo without checking code on github.

Anyway, I really apreshate you keeping this digest module up to date and personaly I think nginx developers should add it to their standard list of modules and or remove the old one from their list and replace with yours.

FYI, this old/existing out of date module is located here...

https://www.nginx.com/resources/wiki/modules/

You may want to send them a quick email and see if they are willing to update their list of modules with yours instead as it would save a lot of people from wasting their time.
